package com.fit2081.Tee_34570403.nutritrack.data.models

import androidx.room.Entity
import androidx.room.PrimaryKey

// Patient Entity
@Entity(tableName = "Patient")
data class Patient (
    /**
     * The unique identifier for the user.
     * It is automatically generated by the database.
     */
    @PrimaryKey
    val userId: Int,

    /** The phone number of a user */
    val phoneNumber: String,

    /** The password of a user */
    val password: String?,

    /**
     * The name of a user.
     */
    val name: String?,

    /**
     * The sex of a user
     */
    val sex: String,

    /**
     * Whether the user is the current app user
     */
    val currentLoggedInUser: Boolean,

    /**
     * Total HEIFA score of a user
     */
    val totalHEIFAScore: Double,

    /**
     * Total Discretionary HEIFA score
     */
    val discretionaryHEIFAScore: Double,

    /**
     * Discretionary Serve Size
     */
    val discretionaryServeSize: Double,

    /**
     * Vegetable HEIFA Score
     */
    val vegetableHEIFAScore: Double,

    /**
     * Vegetables with legumes located serve size
     */
    val vegetablesWithLegumesAllocatedServeSize: Double,

    /**
     * Legumes allocated vegetables
     */
    val legumesAllocatedVegetables: Double,

    /**
     * Vegetables variation score
     */
    val vegetablesVariationScore: Double,

    /**
     * Cruciferous Vegetables
     */
    val vegetablesCruciferous: Double,

    /**
     * Tuber and Bulb Vegetables
     */
    val vegetablesTuberAndBulb: Double,

    /**
     * Other vegetables
     */
    val vegetablesOther: Double,

    /**
     * Legumes
     */
    val legumes: Double,

    /**
     * Green Vegetables
     */
    val vegetablesGreen: Double,

    /**
     * Red and Orange Colour Vegetables
     */
    val vegetablesRedandOrange: Double,

    /**
     * Fruit HEIFA Score
     */
    val fruitHEIFAScore: Double,

    /**
     * Fruit Serve Size
     */
    val fruitServeSize: Double,

    /**
     * Fruit Variation Score
     */
    val fruitVariationScore: Double,

    /**
     * Pome Fruit
     */
    val fruitPome: Double,

    /**
     * Tropical and Subtropical Fruits
     */
    val fruitTropicalAndSubTropical: Double,

    /**
     * Berry Fruits
     */
    val fruitBerry: Double,

    /**
     * Stone Fruits
     */
    val fruitStone: Double,

    /**
     * Citrus Fruits
     */
    val fruitCitrus: Double,

    /**
     * Other Fruits
     */
    val fruitOther: Double,

    /**
     * Grains and Cereals HEIFA Score
     */
    val grainsNCerealsHEIFAScore: Double,

    /**
     * Grains and Cereals Serve Size
     */
    val grainsNCerealsServeSize: Double,

    /**
     * Non Whole Grains
     */
    val grainsNCerealsNonWholeGrains: Double,

    /**
     * Whole Grains HEIFA Score
     */
    val wholeGrainsHEIFAScore: Double,

    /**
     * Whole Grains Serve Size
     */
    val wholeGrainsServeSize: Double,

    /**
     * Meat and Alternatives HEIFA Score
     */
    val meatNAlternativesHEIFAScore: Double,

    /**
     * Meat and Alternatives with Legumes Located Serve Size
     */
    val meatNAlternativesWithLegumesAllocatedServeSize: Double,

    /**
     * Legumes Allocated Meat and Alternatives
     */
    val meatNAlternativesLegumesAllocated: Double,

    /**
     * Dairy and Alternatives HEIFA Score
     */
    val dairyNAlternativesHEIFAScore: Double,

    /**
     * Dairy and Alternatives Serve Size
     */
    val dairyNAlternativesServeSize: Double,

    /**
     * Sodium HEIFA Score
     */
    val sodiumHEIFAScore: Double,

    /**
     * Sodium in Milligrams(mg)
     */
    val sodiumMilligrams: Double,

    /**
     * Alcohol HEIFA Score
     */
    val alcoholHEIFAScore: Double,

    /**
     * Alcohol Standard Drinks
     */
    val alcoholStandardDrinks: Double,

    /**
     * Water HEIFA Score
     */
    val waterHEIFAScore: Double,

    /**
     * Water Consumed
     */
    val water: Double,

    /**
     * Total Amount of Water consumed in ml
     */
    val waterTotalMl: Double,

    /**
     * Total Amount of Beverage consumed in ml
     */
    val beverageTotalMl: Double,

    /**
     * Sugar HEIFA Score
     */
    val sugarHEIFAScore: Double,

    /**
     * Serving Size of Sugar
     */
    val sugar: Double,

    /**
     * Saturated Fat HEIFA Score
     */
    val saturatedFatHEIFAScore: Double,

    /**
     * Serving Size of Saturated Fat
     */
    val saturatedFat: Double,

    /**
     * Unsaturated Fat HEIFA Score
     */
    val unsaturatedFatHEIFAScore: Double,

    /**
     * Unsaturated Fat Serving Size
     */
    val unsaturatedFatServeSize: Double

)